### ISSUE TITLE
Doesn't work with tmux 1.9

### ISSUE THREAD

**Issue by fbertux** [tmux-plugins/tmux-prefix-highlight#6] opened 2016-04-28 12:02 UTC
Hi!

I'm using Debian Jessie and Tmux 1.9 and after commit 8bc5ff3247e0816313e0e65112562f44b2ec6472 plugin stops to work. I'm running the same config with Arch Linux and Tmux 2.2 and plugin works fine. 

What can I do to debug and get this plugin working on Tmux 1.9?

**Comment by erickpintor** [comment] 2016-04-28 12:54
Hi @fbertux 
Thanks for reporting it.

You can try to execute the plugin manually, inside a tmux session:
- Open tmux
- Go to your plugins folder, usually at `~/.tmux/plugins`
- Run `./tmux-prefix-highlight/prefix_highlight.tmux`

That should output an error, if any.

**Comment by fbertux** [comment] 2016-04-28 13:46
Hi @erickpintor 
Thanks for answer.

No errors printed.

If I run set -x prefix_highlight.tmux I get this [output](https://gist.github.com/fbertux/de277b0e9df73729067d58386060e34c) , I don't know if helps.

**Comment by erickpintor** [comment] 2016-04-28 14:21
Yes, that does help.

There seems to be an issue with the interpolation of the new "Copy" highlight:

```
+ tmux set-option -gq status-right '#[fg=colour234,bg=colour234,nobold,nounderscore,noitalics]\
#[fg=colour85,bg=colour234] #{?client_prefix,#{@_prefix_highlight_attr_prefix} ^A ,\
#{?pane_in_mode,#{@_prefix_highlight_attr_copy}Copy,}}#[default] \
#[fg=colour238,bg=colour234,nobold,nounderscore,noitalics]⮂#[fg=colour255,bg=colour238]\
 %b %d %R #[fg=colour190,bg=colour238,nobold,nounderscore,noitalics]\
#[fg=colour17,bg=colour190] #H '
```

Specifically here: `#{@_prefix_highlight_attr_copy}Copy,}}`. Seems like the placeholder was not replaced properly.

Unfortunately, it does not happen in my Mac with Tmux 2.1. I'll have to setup a VM.
Meanwhile, feel free to revert the latest commit from your local. That should fix the problem for now.

**Comment by erickpintor** [comment] 2016-05-02 19:06
Hi @fbertux 
Would you mind testing again? 

After https://github.com/tmux-plugins/tmux-prefix-highlight/commit/b64828f8585c4189a26dbf87d2e9ec1362251e0e, I believe the issue is fixed.

At least, it didn't happened when I tested on a docker image.

**Comment by fbertux** [comment] 2016-05-02 19:12
Hi @erickpintor 

It's working now. 

Thanks!

**Comment by erickpintor** [comment] 2016-05-02 19:27
Cool! I'm closing this issue then.
Até mais.

**Closed by erickpintor** 2016-05-02 19:27 UTC
Labels: bug
